<%
  begin
    require 'dotenv'; Dotenv.load 
  rescue
    $stderr.puts "Could not load dotenv"
  end
%>

driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  aws_ssh_key_id: demandbase-california-20140821
  region: us-west-1
  availability_zone: us-west-1b
  require_chef_omnibus: true
  iam_profile_name:  demandbase-DeployRole-1GA8L14SOS4DV
  ssh_timeout: 10
  ssh_retries: 5
  ebs_volume_size: 6,
  ebs_delete_on_termination: 'true'
  ebs_device_name: '/dev/sda'

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-12.10

suites:
  - name: default
    run_list:
      - recipe[ebs-directory-test]
    attributes:
