<%
  begin
    require 'dotenv'
    Dotenv.load 
  rescue
    $stderr.puts "Could not load dotenv"
  end
%>

driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>
  aws_ssh_key_id: demandbase-east-20130501
  iam_profile_name: test-kitchen
  region: us-east-1
  availability_zone: us-east-1b
  require_chef_omnibus: true
  ssh_timeout: 10
  ssh_retries: 5
  tags:
    Name: test-kitchen-ebs-directory

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
  - name: ubuntu-14.04
    driver: 
      image_id: ami-8caa1ce4
      username: ubuntu
      flavor_id: m1.small

suites:
  - name: default
    run_list:
      - recipe[ebs-directory-test]
    attributes:
